version: "2"
services:
  backend:
    build: ./
    ports:
      - 8000:8000
    # For development
    volumes:
      - ./:/usr/src/app/
    links:
      - vault
    environment:
      VAULT_TOKEN: 60eb71f5-f3fd-7435-ff78-49b7dfae9039
      VAULT_ADDR: http://vault:8200
    command: adev runserver app.py

  vault:
    image: vault
    cap_add:
      - IPC_LOCK
    environment:
      # Warning: don't use this token, or any hardcoded token for that matter
      # but follow the docs on how to properly deploy Vault:
      # https://www.vaultproject.io/intro/getting-started/deploy.html
      VAULT_DEV_ROOT_TOKEN_ID: 60eb71f5-f3fd-7435-ff78-49b7dfae9039
