version: '2'
services:
  backend:
    build: ./
    ports:
      - 8000:8000
    # For development
    volumes:
      - ./:/usr/src/app/
    links:
      - vault
    environment:
      VAULT_TOKEN: 60eb71f5-f3fd-7435-ff78-49b7dfae9039
      VAULT_ADDR: http://vault:8200

  vault:
    image: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 60eb71f5-f3fd-7435-ff78-49b7dfae9039
